apiVersion: v1
kind: Namespace
metadata:
    name: my-elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: my-elasticsearch
    namespace: my-elastic
spec:
    version: 8.7.0
    volumeClaimDeletePolicy: DeleteOnScaledownOnly
    nodeSets:
        -   name: masters
            count: 3
#            podTemplate:
#                spec:
#                    initContainers:
#                        -   name: sysctl
#                            securityContext:
#                                privileged: true
#                                runAsUser: 0
#                            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
                    spec:
                        accessModes:
                            - ReadWriteOnce
                        resources:
                            requests:
                                storage: 5Gi
                        storageClassName: standard
            config:
                # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
                # node.master: true
                node.roles: [ "master" ]
                xpack.ml.enabled: true
                node.remote_cluster_client: false
        -   name: data
            count: 3
#            podTemplate:
#                spec:
#                    initContainers:
#                        -   name: sysctl
#                            securityContext:
#                                privileged: true
#                                runAsUser: 0
#                            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
                    spec:
                        accessModes:
                            - ReadWriteOnce
                        resources:
                            requests:
                                storage: 5Gi
                        storageClassName: standard
            config:
                # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
                # node.master: false
                # node.data: true
                # node.ingest: true
                # node.ml: true
                # node.transform: true
                node.roles: [ "data", "ingest", "ml", "transform" ]
                node.remote_cluster_client: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
    name: my-kibana
    namespace: my-elastic
spec:
    version: 8.7.0
    count: 1
    elasticsearchRef:
        name: my-elasticsearch