apiVersion: v1
data:
    allow-snippet-annotations: "true"
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "proxyUpstreamName":
      "$proxy_upstream_name", "proxyAlternativeUpstreamName": "$proxy_alternative_upstream_name","upstreamStatus":
      "$upstream_status", "upstreamAddr": "$upstream_addr","httpRequest":{"requestMethod":
      "$request_method", "requestUrl": "$host$request_uri", "status": $status,"requestSize":
      "$request_length", "responseSize": "$upstream_response_length", "userAgent": "$http_user_agent",
      "remoteIp": "$remote_addr", "referer": "$http_referer", "latency": "$upstream_response_time s",
      "protocol":"$server_protocol"}}'
kind: ConfigMap
metadata:
    labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
        app.kubernetes.io/version: 1.7.0
        helm.sh/chart: ingress-nginx-4.6.0
    name: ingress-nginx-controller
    namespace: ingress-nginx
